version: '3.8'

services:
  backend:
    build:
      context: ./HotelDB
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    volumes:
      - ./HotelDB:/app
      - ./HotelDB/media:/app/media
      - static_volume:/app/staticfiles
      - media_data:/app/media
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=HotelDB.settings
      - MYSQL_DATABASE=bd
      - MYSQL_USER=hotel_user
      - MYSQL_PASSWORD=1234
      - MYSQL_HOST=db
      - ALLOWED_HOSTS=78.24.223.206,localhost,127.0.0.1
    command: >
      sh -c "python manage.py migrate &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8086"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./hotel-frontend
      dockerfile: Dockerfile
    ports:
      - "3003:80"
    volumes:
      - ./hotel-frontend:/app
      - /app/node_modules
      - media_data:/app/media
    environment:
      - REACT_APP_API_URL=http://78.24.223.206:8086
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=bd
      - MYSQL_USER=hotel_user
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mysql_data:
  static_volume:
  media_data:
